# TODO: Block break reward editor
enabled: false
log: true

# Example theoretical config:
blocks:
  iron_block:
    - netherite_block:
        Type: Vanilla
        Amount: 1
        Chance: 5
  grass_block:
    - amethyst_sword:
        Type: Oraxen
        Amount: 1
        Chance: 10
  stone:
    - CUTLASS:
        Type: MMOItems
        Category: SWORD
        Amount: 1
        Chance: 50