# TODO: Village trade editor
enabled: false
log: true

# Example theoretical config:
MASON:
  - amethyst_sword:
      Type: Oraxen
      Reward_xp: 15
      slot_one:
        emerald:
          amount: 4
      slot_two:
        diamond:
          amount: 10

  - netherite_sword:
      Type: Vanilla
      Reward_xp: 10
      slot_one:
        netherite_ingot:
          amount: 2
      slot_two:
        coal:
          amount: 64

  - CUTLASS:
      Type: MMOItems
      Category: SWORD
      reward_xp: 30
      slot_one:
        netherite_ingot:
          amount: 2
      slot_two:
        coal:
          amount: 64

FLETCHER:
  # Same here as well